services:
  - type: web
    name: evolution-api-qr
    runtime: image
    image:
      url: ghcr.io/danielcardeenas/evolution-api:2.2.3-full
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        value: alguma_senha_segura
      - key: DATABASE_PROVIDER
        value: sqlite
      - key: AUTHENTICATION_TYPE
        value: apikey
      - key: AUTHENTICATION_API_KEY
        value: tua_api_key
